'use strict'
const assert=require('node:assert/strict')
const path=require('node:path')
const http=require('node:http')
const fs=require('node:fs')

// Runs only against the disposable suite's API/database. Never signs in to or
// creates fixture customers in the configured local/Supabase deployment.
async function browserChecks(session, tenantFixture) {
  const frontend=path.resolve(__dirname,'../../../frontend')
  const {chromium}=require(path.join(frontend,'node_modules/playwright'))
  const app=require('express')()
  app.use('/api',(req,res)=>{
    const proxy=http.request('http://127.0.0.1:15550'+req.originalUrl,{method:req.method,headers:req.headers},response=>{
      res.writeHead(response.statusCode,response.headers);response.pipe(res)
    })
    proxy.on('error',()=>res.status(502).end());req.pipe(proxy)
  })
  app.use(require('express').static(path.join(frontend,'dist')))
  app.use((req,res)=>res.sendFile(path.join(frontend,'dist/index.html')))
  const server=await new Promise((resolve,reject)=>{const running=app.listen(15551,'127.0.0.1',()=>resolve(running));running.once('error',reject)})
  let browser, page
  const requests=[]
  try {
    browser=await chromium.launch({headless:true,channel:'chrome'})
    const context=await browser.newContext({viewport:{width:1440,height:1000}})
    const errors=[]
    page=await context.newPage()
    page.setDefaultTimeout(60000)
    page.on('pageerror',error=>errors.push(error.message))
    await context.route('**/*',route=>{
      const url=new URL(route.request().url())
      if(url.pathname.startsWith('/api/')) return route.continue({url:'http://127.0.0.1:15550'+url.pathname+url.search})
      if(['http:','https:'].includes(url.protocol) && !['http://127.0.0.1:15550','http://127.0.0.1:15551'].includes(url.origin)) return route.abort()
      return route.continue()
    })
    await context.addInitScript(value=>{
      localStorage.setItem('flowsphere_token',value.token)
      localStorage.setItem('flowsphere_user',JSON.stringify(value.user))
      localStorage.setItem('fs.userGuide.completed.'+value.user._id,'1')
    },session)
    await page.goto('http://127.0.0.1:15551/platform',{waitUntil:'domcontentloaded'})
    await page.getByRole('button',{name:'Create organization',exact:true}).click()
    await page.getByLabel('Organization Name',{exact:true}).fill('Browser Retry Fixture')
    await page.getByLabel('Admin email',{exact:true}).fill('browser@qa.test')
    await page.getByLabel('Billing email',{exact:false}).fill('billing@qa.test')
    // External domains are allowed only for this isolated test workspace.
    const domainInput=page.getByLabel('Allowed Domains',{exact:true})
    if(await domainInput.count()) await domainInput.fill('qa.test')
    let loseResponse=true
    await page.route('**/api/platform/orgs',async route=>{
      const target='http://127.0.0.1:15550/api/platform/orgs'
      if(route.request().method()!=='POST') return route.continue({url:target})
      requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()})
      if(loseResponse) {
        loseResponse=false
        const response=await route.fetch({url:target,timeout:60000})
        assert.equal(response.status(),201,'The lost response committed successfully')
        return route.abort('connectionfailed')
      }
      return route.continue({url:target})
    })
    await page.getByRole('dialog').getByRole('button',{name:'Create organization',exact:true}).click()
    await page.getByRole('button',{name:'Retry setup',exact:true}).waitFor()
    await page.getByRole('button',{name:'Retry setup',exact:true}).click()
    await page.getByRole('heading',{name:'New organization',exact:true}).waitFor({state:'hidden'})
    assert.equal(requests.length,2)
    assert.deepEqual(requests[0],requests[1],'Network retry keeps its address, payload and request ID')
    await page.getByRole('row').filter({hasText:'Browser Retry Fixture'}).waitFor()
    assert.equal(await page.getByText('Temporary password',{exact:true}).count(),0,'Replay never re-exposes credentials')
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    await page.getByRole('menuitem',{name:'Edit organization',exact:true}).click()
    await page.getByLabel('Billing email',{exact:false}).fill('phase5-billing@qa.test')
    const edited=page.waitForResponse(r=>r.url().includes('/api/platform/orgs/') && r.request().method()==='PUT')
    await page.getByRole('button',{name:'Save changes',exact:true}).click()
    const updated=await edited
    assert.equal(updated.status(),200,'Existing organization edit UI saves through scoped platform management')
    assert.equal((await updated.json()).org.billingEmail,'phase5-billing@qa.test')
    await page.getByRole('dialog').waitFor({state:'hidden'})
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    await page.getByRole('menuitem',{name:'Suspend organization',exact:true}).click()
    const suspended=page.waitForResponse(r=>r.url().endsWith('/suspend') && r.request().method()==='POST')
    await page.getByRole('button',{name:'Suspend',exact:true}).click()
    assert.equal((await suspended).status(),200)
    await page.getByRole('dialog').waitFor({state:'hidden'})
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    const activated=page.waitForResponse(r=>r.url().endsWith('/activate') && r.request().method()==='POST')
    await page.getByRole('menuitem',{name:'Reactivate organization',exact:true}).click()
    assert.equal((await activated).status(),200)
    console.log('PASS: existing browser organization edit, suspend and reactivate controls')
    const row=page.getByRole('row').filter({hasText:'Browser Retry Fixture'})
    const storageResponse=page.waitForResponse(r=>/\/api\/platform\/orgs\/[a-f0-9]{24}\/storage$/.test(new URL(r.url()).pathname))
    await row.getByRole('button',{name:'View details',exact:true}).click()
    const storageConfig=await storageResponse
    assert.equal(storageConfig.status(),200,'Organization storage configuration: '+(await storageConfig.json()).code)
    await page.getByRole('heading',{name:'Organization documents',exact:true}).waitFor()
    await page.getByRole('combobox',{name:'Storage connection',exact:true}).waitFor()
    await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click()
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    await page.getByRole('menuitem',{name:'Suspend organization',exact:true}).click()
    const suspendedAgain=page.waitForResponse(r=>r.url().endsWith('/suspend') && r.request().method()==='POST')
    await page.getByRole('button',{name:'Suspend',exact:true}).click();assert.equal((await suspendedAgain).status(),200)
    await page.getByRole('dialog').waitFor({state:'hidden'})
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    await page.getByRole('menuitem',{name:'Archive organization',exact:true}).click()
    await page.getByLabel('Retention period (days)',{exact:true}).fill('30')
    await page.getByLabel('Reason',{exact:true}).fill('Isolated browser verification')
    await page.getByLabel('Type Browser Retry Fixture to confirm',{exact:true}).fill('Browser Retry Fixture')
    const phase6Screens=path.resolve(frontend,'../output/verification')
    fs.mkdirSync(phase6Screens,{recursive:true})
    await page.getByRole('dialog').screenshot({path:path.join(phase6Screens,'phase-6-archive.png')})
    const archived=page.waitForResponse(r=>r.url().endsWith('/archive') && r.request().method()==='POST')
    await page.getByRole('button',{name:'Archive organization',exact:true}).click();assert.equal((await archived).status(),200)
    await page.getByRole('dialog').waitFor({state:'hidden'})
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    const restored=page.waitForResponse(r=>r.url().endsWith('/restore-archive'))
    await page.getByRole('menuitem',{name:'Restore archive',exact:true}).click();assert.equal((await restored).status(),200)
    await page.getByRole('button',{name:'More actions for Browser Retry Fixture',exact:true}).click()
    const reactivated=page.waitForResponse(r=>r.url().endsWith('/activate'))
    await page.getByRole('menuitem',{name:'Reactivate organization',exact:true}).click();assert.equal((await reactivated).status(),200)
    await page.goto('http://127.0.0.1:15551/dashboard',{waitUntil:'domcontentloaded'})
    await page.getByRole('heading',{name:'Organization announcements',exact:true}).waitFor()
    await page.getByRole('combobox',{name:'Audience',exact:true}).selectOption('all')
    await page.getByLabel('Message',{exact:true}).fill('Isolated browser announcement')
    await page.getByLabel('Expires at (your local time)',{exact:true}).fill('2099-12-31T12:00')
    const broadcast=page.waitForResponse(r=>r.url().endsWith('/platform/broadcast'))
    await page.getByRole('button',{name:'Publish announcement',exact:true}).click();assert.equal((await broadcast).status(),201)
    await page.getByText('Announcement published to the selected audience.',{exact:true}).waitFor()
    await page.getByRole('heading',{name:'Organization announcements',exact:true}).scrollIntoViewIfNeeded()
    await page.getByRole('heading',{name:'Organization announcements',exact:true}).locator('..').screenshot({path:path.join(phase6Screens,'phase-6-announcement.png')})
    await page.goto('http://127.0.0.1:15551/plans',{waitUntil:'domcontentloaded'})
    await page.getByRole('button',{name:'Create plan',exact:true}).click()
    await page.getByLabel('Plan name',{exact:true}).fill('Browser Operations Plan')
    await page.getByLabel('Plan key',{exact:true}).fill('browser-operations-plan')
    const planCreated=page.waitForResponse(r=>r.url().endsWith('/platform/plans') && r.request().method()==='POST')
    await page.getByRole('dialog').getByRole('button',{name:'Create plan',exact:true}).click()
    assert.equal((await planCreated).status(),201)
    await page.getByRole('button',{name:'Delete Browser Operations Plan',exact:true}).click()
    await page.getByRole('alertdialog').waitFor()
    await page.getByRole('alertdialog').screenshot({path:path.join(phase6Screens,'phase-6-plan-removal.png')})
    const planDeleted=page.waitForResponse(r=>r.url().endsWith('/platform/plans/browser-operations-plan') && r.request().method()==='DELETE')
    await page.getByRole('alertdialog').getByRole('button',{name:'Delete plan',exact:true}).click()
    assert.equal((await planDeleted).status(),200)
    await page.getByRole('button',{name:'Delete Browser Operations Plan',exact:true}).waitFor({state:'hidden'})
    await page.goto('http://127.0.0.1:15551/platform',{waitUntil:'domcontentloaded'})
    await page.getByRole('row').filter({hasText:'Browser Retry Fixture'}).waitFor()
    console.log('PASS: browser organization storage selector, archive/restore, announcement publish and unused plan removal')

    await page.setViewportSize({width:390,height:844})
    const matches=page.getByText('Browser Retry Fixture',{exact:true})
    assert.ok((await Promise.all(Array.from({length:await matches.count()},(_,i)=>matches.nth(i).isVisible()))).some(Boolean))
    assert.deepEqual(errors,[],'No browser runtime errors')
    console.log('PASS: browser organization form, real committed/lost response, stable retry UUID/address, replay feedback and mobile list')
    if (tenantFixture) {
      const tenantContext = await browser.newContext({ viewport: { width: 390, height: 844 } })
      await tenantContext.route('**/*', route => {
        const url = new URL(route.request().url())
        if (url.pathname.startsWith('/api/')) return route.continue({ url: 'http://127.0.0.1:15550' + url.pathname + url.search })
        if (['http:', 'https:'].includes(url.protocol) && url.origin !== 'http://127.0.0.1:15551') return route.abort()
        return route.continue()
      })
      const signIn = await tenantContext.newPage()
      signIn.setDefaultTimeout(60000)
      signIn.on('pageerror', error => errors.push(error.message))
      await tenantContext.addInitScript(workspace => localStorage.setItem('netflow_workspace', workspace), tenantFixture.workspace)
      await signIn.goto('http://127.0.0.1:15551/login', { waitUntil: 'domcontentloaded' })
      const noSelector = async () => {
        assert.equal(await signIn.getByRole('combobox').count(), 0, 'No account selector')
        assert.equal(await signIn.locator('#account-workspace').count(), 0, 'No workspace input')
      }
      await noSelector()
      await signIn.getByLabel('Email address', { exact: true }).fill(tenantFixture.email)
      await signIn.getByLabel('Password', { exact: true }).fill(tenantFixture.password)
      const deniedResponse = signIn.waitForResponse(response => response.url().includes('/api/auth/login') && response.request().method() === 'POST')
      await signIn.getByRole('button', { name: 'Sign In', exact: true }).click()
      const denied = await deniedResponse
      assert.equal(denied.status(), 401, 'A remembered workspace cannot silently route a bare login')
      assert.equal(denied.request().postDataJSON().subdomain, undefined)
      await signIn.getByRole('alert').filter({ hasText: 'Invalid email or password' }).waitFor()
      await noSelector()
      assert.ok(await signIn.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile sign-in fits viewport')
      const screenshots = path.resolve(frontend, '../output/verification')
      fs.mkdirSync(screenshots, { recursive: true })
      await signIn.screenshot({ path: path.join(screenshots, 'phase-3-login-mobile.png'), fullPage: true })
      await signIn.setViewportSize({ width: 1366, height: 768 })
      await signIn.goto('http://127.0.0.1:15551/login', { waitUntil: 'domcontentloaded' })
      await signIn.getByLabel('Email address', { exact: true }).waitFor()
      await signIn.screenshot({ path: path.join(screenshots, 'phase-3-login-desktop.png'), fullPage: true })
      await signIn.goto('http://127.0.0.1:15551/login?org=' + encodeURIComponent(tenantFixture.workspace), { waitUntil: 'domcontentloaded' })
      await signIn.getByRole('link', { name: 'Forgot Password?', exact: true }).click()
      await signIn.getByLabel('Work email', { exact: true }).waitFor()
      await noSelector()
      await signIn.getByRole('link', { name: 'Back to sign in', exact: true }).click()
      assert.equal(new URL(signIn.url()).searchParams.get('org'), tenantFixture.workspace, 'Recovery preserves the explicit login link')
      await noSelector()
      await signIn.getByLabel('Email address', { exact: true }).fill(tenantFixture.email)
      await signIn.getByLabel('Password', { exact: true }).fill(tenantFixture.password)
      const loginResponse = signIn.waitForResponse(response => response.url().includes('/api/auth/login') && response.request().method() === 'POST')
      await signIn.getByRole('button', { name: 'Sign In', exact: true }).click()
      assert.equal((await loginResponse).status(), 200)
      await signIn.waitForURL(url => !url.pathname.includes('login'))
      assert.equal(await signIn.evaluate(() => JSON.parse(localStorage.getItem('flowsphere_user')).orgId), tenantFixture.orgId)
      // This fixture already completed onboarding through the API. The separate
      // browser-only guide must also be marked complete before navigating; its
      // delayed first-step redirect otherwise hides the forms page after render.
      await signIn.evaluate(() => {
        const user = JSON.parse(localStorage.getItem('flowsphere_user'))
        localStorage.setItem('fs.userGuide.completed.' + user._id, '1')
      })
      await signIn.setViewportSize({ width: 1440, height: 1000 })
      await signIn.goto('http://127.0.0.1:15551/forms', { waitUntil: 'domcontentloaded' })
      await signIn.getByText('Tenant isolation form', { exact: true }).first().waitFor()
      assert.equal(new URL(signIn.url()).pathname, '/forms')
      await signIn.screenshot({ path: path.join(screenshots, 'phase-3-tenant-forms.png'), fullPage: true })
      assert.deepEqual(errors, [], 'No tenant sign-in/browser runtime errors')
      await tenantContext.close()
      console.log('PASS: email/password-only login and recovery, generic ambiguity response, explicit-link routing, stale workspace rejection and tenant forms')
    }
  } catch(error) {
    if(page) console.log(JSON.stringify({browserFailure:true,creationRequests:requests.length,
      buttons:await page.getByRole('button').allTextContents(),
      invalid:await page.locator('input:invalid').evaluateAll(nodes=>nodes.map(n=>({type:n.type,message:n.validationMessage}))),
      feedback:await page.getByRole('status').allTextContents(),alerts:await page.getByRole('alert').allTextContents()}))
    throw error
  } finally {
    await browser?.close()
    server.closeAllConnections()
    await new Promise(resolve=>server.close(resolve))
  }
}
module.exports={browserChecks}
