// One-click form templates for the "New form" chooser.
// Field shapes mirror FIELD_TYPES in NewForm.jsx. The builder assigns real
// field ids (newFieldId) and grid column ids (freshColumns) when a template
// is loaded, so the ids below are placeholders only.
export const FORM_TEMPLATES = [
  {
    id: 'leave-approval',
    name: 'Leave Approval',
    category: 'HR',
    description: 'Time-off request with leave type, dates and reason.',
    fields: [
      { type: 'text', label: 'Employee name', placeholder: 'Jane Doe', required: true },
      { type: 'dropdown', label: 'Leave type', required: true, options: ['Annual leave', 'Sick leave', 'Casual leave', 'Maternity/Paternity'] },
      { type: 'date', label: 'Start date', required: true },
      { type: 'date', label: 'End date', required: true },
      { type: 'text', label: 'Reason', placeholder: 'Briefly explain', required: false, multiline: true, maxLength: 300 },
      { type: 'file', label: 'Supporting document', required: false, fileTypes: 'PDF / DOCX', maxSize: 5 },
    ],
  },
  {
    id: 'purchase-request',
    name: 'Purchase Request',
    category: 'Finance',
    description: 'Request to buy goods or services with line items.',
    fields: [
      { type: 'text', label: 'Requested by', required: true },
      { type: 'dropdown', label: 'Department', required: true, options: ['HR', 'Finance', 'IT', 'Operations', 'Sales', 'Legal'] },
      { type: 'grid', label: 'Items', required: true, columns: [
        { id: 'c1', label: 'Item', type: 'text' },
        { id: 'c2', label: 'Qty', type: 'number' },
        { id: 'c3', label: 'Unit price', type: 'number' },
      ] },
      { type: 'number', label: 'Estimated total', required: false },
      { type: 'dropdown', label: 'Priority', required: false, options: ['Low', 'Medium', 'High', 'Urgent'] },
      { type: 'text', label: 'Justification', required: false, multiline: true },
      { type: 'file', label: 'Quotation', required: false, fileTypes: 'PDF', maxSize: 5 },
    ],
  },
  {
    id: 'expense-reimbursement',
    name: 'Expense Reimbursement',
    category: 'Finance',
    description: 'Claim back business expenses with itemised receipts.',
    fields: [
      { type: 'text', label: 'Employee name', required: true },
      { type: 'text', label: 'Employee ID', required: false },
      { type: 'date', label: 'Expense date', required: true },
      { type: 'grid', label: 'Expenses', required: true, columns: [
        { id: 'c1', label: 'Description', type: 'text' },
        { id: 'c2', label: 'Category', type: 'dropdown', options: ['Travel', 'Meals', 'Lodging', 'Supplies', 'Other'] },
        { id: 'c3', label: 'Amount', type: 'number' },
      ] },
      { type: 'number', label: 'Total amount', required: true },
      { type: 'file', label: 'Receipts', required: true, fileTypes: 'PDF / JPG / PNG', maxSize: 10 },
      { type: 'checkbox', label: 'I confirm these expenses are accurate', required: true },
    ],
  },
  {
    id: 'travel-request',
    name: 'Travel Request',
    category: 'Operations',
    description: 'Approval for business travel and estimated budget.',
    fields: [
      { type: 'text', label: 'Traveler name', required: true },
      { type: 'dropdown', label: 'Trip type', required: false, options: ['Domestic', 'International'] },
      { type: 'text', label: 'Destination', required: true },
      { type: 'date', label: 'Departure date', required: true },
      { type: 'date', label: 'Return date', required: true },
      { type: 'text', label: 'Purpose of travel', required: true, multiline: true },
      { type: 'number', label: 'Estimated budget', required: false },
      { type: 'checkbox', label: 'Accommodation required', required: false },
      { type: 'file', label: 'Invitation / approval letter', required: false, fileTypes: 'PDF', maxSize: 5 },
    ],
  },
  {
    id: 'it-support-ticket',
    name: 'IT Support Ticket',
    category: 'IT',
    description: 'Report an IT issue and set its priority.',
    fields: [
      { type: 'text', label: 'Your name', required: true },
      { type: 'text', label: 'Email', required: true },
      { type: 'dropdown', label: 'Issue category', required: true, options: ['Hardware', 'Software', 'Network', 'Account access', 'Email', 'Other'] },
      { type: 'radio', label: 'Priority', required: true, options: ['Low', 'Medium', 'High', 'Critical'] },
      { type: 'text', label: 'Description', required: true, multiline: true },
      { type: 'file', label: 'Screenshot / attachment', required: false, fileTypes: 'JPG / PNG / PDF', maxSize: 10 },
    ],
  },
  {
    id: 'employee-onboarding',
    name: 'Employee Onboarding',
    category: 'HR',
    description: 'Collect new-hire details and signed documents.',
    fields: [
      { type: 'text', label: 'Full name', required: true },
      { type: 'text', label: 'Personal email', required: true },
      { type: 'text', label: 'Phone number', required: false },
      { type: 'date', label: 'Start date', required: true },
      { type: 'dropdown', label: 'Department', required: true, options: ['HR', 'Finance', 'IT', 'Operations', 'Sales', 'Legal'] },
      { type: 'text', label: 'Job title', required: true },
      { type: 'file', label: 'ID proof', required: true, fileTypes: 'PDF / JPG / PNG', maxSize: 5 },
      { type: 'file', label: 'Signed offer letter', required: true, fileTypes: 'PDF', maxSize: 10 },
      { type: 'signature', label: 'Employee signature', required: true },
    ],
  },
  {
    id: 'document-submission',
    name: 'Document Submission',
    category: 'Company-wide',
    description: 'Submit a document for review or record-keeping.',
    fields: [
      { type: 'text', label: 'Document title', required: true },
      { type: 'dropdown', label: 'Document type', required: false, options: ['Policy', 'Report', 'Contract', 'Invoice', 'Other'] },
      { type: 'text', label: 'Description', required: false, multiline: true },
      { type: 'file', label: 'Attachment', required: true, fileTypes: 'PDF / DOCX', maxSize: 10 },
      { type: 'date', label: 'Submission date', required: false },
    ],
  },
  {
    id: 'vendor-registration',
    name: 'Vendor Registration',
    category: 'Operations',
    description: 'Onboard a new supplier with company and bank details.',
    fields: [
      { type: 'text', label: 'Company name', required: true },
      { type: 'text', label: 'Contact person', required: true },
      { type: 'text', label: 'Email', required: true },
      { type: 'text', label: 'Phone', required: true },
      { type: 'dropdown', label: 'Category of supply', required: false, options: ['Goods', 'Services', 'Both'] },
      { type: 'text', label: 'Address', required: false, multiline: true },
      { type: 'text', label: 'Tax / GST number', required: false },
      { type: 'file', label: 'Company registration document', required: true, fileTypes: 'PDF', maxSize: 10 },
      { type: 'file', label: 'Bank details', required: false, fileTypes: 'PDF', maxSize: 5 },
    ],
  },
  {
    id: 'performance-review',
    name: 'Performance Review',
    category: 'HR',
    description: 'Periodic employee evaluation with ratings and sign-off.',
    fields: [
      { type: 'text', label: 'Employee name', required: true },
      { type: 'text', label: 'Reviewer name', required: true },
      { type: 'dropdown', label: 'Review period', required: false, options: ['Q1', 'Q2', 'Q3', 'Q4', 'Annual'] },
      { type: 'grid', label: 'Ratings', required: false, columns: [
        { id: 'c1', label: 'Competency', type: 'text' },
        { id: 'c2', label: 'Rating (1-5)', type: 'number' },
        { id: 'c3', label: 'Comments', type: 'text' },
      ] },
      { type: 'text', label: 'Strengths', required: false, multiline: true },
      { type: 'text', label: 'Areas to improve', required: false, multiline: true },
      { type: 'radio', label: 'Overall rating', required: true, options: ['Exceeds expectations', 'Meets expectations', 'Below expectations'] },
      { type: 'signature', label: 'Reviewer signature', required: true },
    ],
  },
  {
    id: 'asset-request',
    name: 'Asset / Equipment Request',
    category: 'IT',
    description: 'Request hardware or equipment for an employee.',
    fields: [
      { type: 'text', label: 'Requested by', required: true },
      { type: 'dropdown', label: 'Department', required: false, options: ['HR', 'Finance', 'IT', 'Operations', 'Sales', 'Legal'] },
      { type: 'grid', label: 'Items requested', required: true, columns: [
        { id: 'c1', label: 'Asset', type: 'dropdown', options: ['Laptop', 'Monitor', 'Keyboard', 'Mouse', 'Phone', 'Other'] },
        { id: 'c2', label: 'Quantity', type: 'number' },
        { id: 'c3', label: 'Notes', type: 'text' },
      ] },
      { type: 'text', label: 'Reason', required: true, multiline: true },
      { type: 'date', label: 'Needed by', required: false },
      { type: 'checkbox', label: 'Manager approval obtained', required: false },
    ],
  },
  {
    id: 'customer-feedback',
    name: 'Customer Feedback',
    category: 'Sales',
    description: 'Collect satisfaction ratings and comments.',
    fields: [
      { type: 'text', label: 'Name', required: false },
      { type: 'text', label: 'Email', required: false },
      { type: 'radio', label: 'How satisfied are you?', required: true, options: ['Very satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very dissatisfied'] },
      { type: 'dropdown', label: 'Which product / service?', required: false, options: ['Product A', 'Product B', 'Support', 'Other'] },
      { type: 'text', label: 'Comments', required: false, multiline: true },
      { type: 'checkbox', label: 'May we contact you about this feedback?', required: false },
    ],
  },
  {
    id: 'incident-report',
    name: 'Incident / Complaint Report',
    category: 'Legal',
    description: 'Report an incident with evidence and sign-off.',
    fields: [
      { type: 'text', label: 'Reported by', required: true },
      { type: 'date', label: 'Date of incident', required: true },
      { type: 'text', label: 'Location', required: false },
      { type: 'dropdown', label: 'Incident type', required: true, options: ['Safety', 'Harassment', 'Theft', 'Property damage', 'Other'] },
      { type: 'text', label: 'Description', required: true, multiline: true },
      { type: 'file', label: 'Evidence (photos / docs)', required: false, fileTypes: 'JPG / PNG / PDF', maxSize: 10 },
      { type: 'checkbox', label: 'I confirm this report is accurate', required: true },
      { type: 'signature', label: 'Signature', required: false },
    ],
  },
]
